#region

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

#endregion

namespace UniConfig.Editor
{
    internal sealed class CsharpConfigFileGenerator
    {
        public const string FileName = "Cfg.g.cs";
        private readonly string _exportDirectory;

        private readonly IReadOnlyList<ConfigModule> _modules;
        private readonly string _rootNamespace;

        public CsharpConfigFileGenerator(IReadOnlyList<ConfigModule> modules, string rootNamespace,
            string exportDirectory)
        {
            _modules = modules ?? throw new ArgumentNullException(nameof(modules));
            _rootNamespace = string.IsNullOrWhiteSpace(rootNamespace) ? "Game.Config" : rootNamespace.Trim();
            _exportDirectory = exportDirectory ?? throw new ArgumentNullException(nameof(exportDirectory));
        }

        public string Generate()
        {
            string relativeDir = _exportDirectory.Replace('\\', '/').TrimEnd('/');
            if (!relativeDir.StartsWith("Assets/", StringComparison.Ordinal) &&
                !relativeDir.Equals("Assets", StringComparison.Ordinal))
                throw new InvalidOperationException($"C# 导出目录必须位于 Assets 下: {_exportDirectory}");

            string absoluteDir = Path.Combine(ConfigPaths.ProjectRoot,
                relativeDir.Replace('/', Path.DirectorySeparatorChar));
            ConfigPaths.EnsureDirectory(absoluteDir);

            AssignTableIds();

            StringBuilder sb = new(4096);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// 此文件由 UniConfig 自动生成，请勿手动修改。");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using MemoryPack;");
            sb.AppendLine("using UniConfig;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.Append("namespace ").Append(_rootNamespace).AppendLine();
            sb.AppendLine("{");

            List<(string className, string fullName, string tableName, int tableId)> generated = new();
            HashSet<string> generatedClassNames = new(StringComparer.Ordinal);
            foreach (ConfigModule module in _modules)
            {
                if (module?.tables == null) continue;
                foreach (ConfigTable table in module.tables)
                {
                    if (table == null) continue;
                    ValidateTable(table);
                    string className = GetClassName(table.tableName);
                    if (!generatedClassNames.Add(className))
                        throw new InvalidOperationException(
                            $"重复的配置类名: {className}（表 {table.moduleName}/{table.tableName}）");

                    string fullName = $"{_rootNamespace}.{className}";
                    AppendClass(sb, table, className);
                    table.mapCsharpTypeFullName = fullName;
                    generated.Add((className, fullName, table.tableName, table.tableId));
                }
            }

            AppendCfgStaticClass(sb, generated);
            sb.AppendLine("}");

            string filePath = Path.Combine(absoluteDir, FileName);
            File.WriteAllText(filePath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log($"[UniConfig] 已生成 {filePath}");
            return filePath;
        }

        /// <summary>
        /// 为尚未分配 Id 的表自增分配，并校验全局唯一。已有 Id 保持不变，保证二进制兼容。
        /// </summary>
        private void AssignTableIds()
        {
            HashSet<int> used = new();
            int nextId = 1;

            foreach (ConfigModule module in _modules)
            {
                if (module?.tables == null) continue;
                foreach (ConfigTable table in module.tables)
                {
                    if (table == null || table.tableId <= 0) continue;
                    if (!used.Add(table.tableId))
                        throw new InvalidOperationException(
                            $"表唯一 Id 冲突: {table.tableId}（{table.moduleName}/{table.tableName}）");

                    if (table.tableId >= nextId)
                        nextId = table.tableId + 1;
                }
            }

            foreach (ConfigModule module in _modules)
            {
                if (module?.tables == null) continue;
                foreach (ConfigTable table in module.tables)
                {
                    if (table == null) continue;
                    if (table.tableId > 0) continue;
                    table.tableId = nextId++;
                    used.Add(table.tableId);
                }
            }
        }

        public static string GetClassName(string tableName)
        {
            return "Cfg" + tableName;
        }

        private static void ValidateTable(ConfigTable table)
        {
            if (!FieldUtils.IsValidIdentifier(table.tableName))
                throw new InvalidOperationException($"表名不是合法 C# 标识符: {table.tableName}");

            if (table.fields == null || table.fields.Count == 0)
                throw new InvalidOperationException($"表 {table.moduleName}/{table.tableName} 没有任何字段，无法生成配置类");

            if (table.tableId <= 0)
                throw new InvalidOperationException($"表 {table.moduleName}/{table.tableName} 缺少有效 tableId");

            HashSet<string> names = new(StringComparer.Ordinal);
            foreach (ConfigField field in table.fields)
            {
                if (!FieldUtils.IsValidIdentifier(field.name))
                    throw new InvalidOperationException($"字段名不是合法 C# 标识符: {table.tableName}.{field.name}");
                if (!names.Add(field.name))
                    throw new InvalidOperationException($"表 {table.tableName} 存在重复字段: {field.name}");
                if (field.type == SupportableFieldType.Enum)
                {
                    if (string.IsNullOrEmpty(field.enumTypeFullName))
                        throw new InvalidOperationException(
                            $"表 {table.tableName} 字段 {field.name} 为枚举但未指定 enumTypeFullName");
                    EnumTypeUtil.ResolveOrThrow(field.enumTypeFullName);
                }
            }
        }

        private static void AppendClass(StringBuilder sb, ConfigTable table, string className)
        {
            sb.AppendLine("    [MemoryPackable]");
            sb.Append("    public sealed partial class ").Append(className).Append(" : IConfigTable").AppendLine();
            sb.AppendLine("    {");

            foreach (ConfigField field in table.fields)
                sb.Append("        public readonly ")
                    .Append(FieldUtils.GetCsharpTypeName(field))
                    .Append(' ')
                    .Append(field.name)
                    .AppendLine(";");

            sb.AppendLine();
            sb.Append("        public ").Append(className).Append('(');
            for (int i = 0; i < table.fields.Count; i++)
            {
                ConfigField field = table.fields[i];
                if (i > 0) sb.Append(", ");
                sb.Append(FieldUtils.GetCsharpTypeName(field)).Append(' ').Append(field.name);
            }

            sb.AppendLine(")");
            sb.AppendLine("        {");
            foreach (ConfigField field in table.fields)
                sb.Append("            this.").Append(field.name).Append(" = ").Append(field.name).AppendLine(";");
            sb.AppendLine("        }");

            AppendToString(sb, table, className);
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendToString(StringBuilder sb, ConfigTable table, string className)
        {
            sb.AppendLine();
            sb.AppendLine("        public override string ToString()");
            sb.AppendLine("        {");
            sb.Append("            return nameof(").Append(className).Append(") + \" { \"");
            for (int i = 0; i < table.fields.Count; i++)
            {
                ConfigField field = table.fields[i];
                if (i > 0)
                    sb.Append(" + \", \"");
                sb.Append(" + \"").Append(field.name).Append(" = \" + ");
                sb.Append(FormatFieldExpression(field));
            }

            sb.AppendLine(" + \" }\";");
            sb.AppendLine("        }");
        }

        private static string FormatFieldExpression(ConfigField field)
        {
            switch (field.type)
            {
                case SupportableFieldType.String:
                    return $"({field.name} ?? \"null\")";
                case SupportableFieldType.Single:
                case SupportableFieldType.Double:
                    return $"Cfg.Num({field.name})";
                case SupportableFieldType.Array1D_Int16:
                case SupportableFieldType.Array1D_Int32:
                case SupportableFieldType.Array1D_Int64:
                case SupportableFieldType.Array1D_UInt16:
                case SupportableFieldType.Array1D_UInt32:
                case SupportableFieldType.Array1D_UInt64:
                case SupportableFieldType.Array1D_Boolean:
                    return $"Cfg.Arr({field.name})";
                case SupportableFieldType.Array1D_Single:
                    return $"Cfg.ArrF({field.name})";
                case SupportableFieldType.Array1D_Double:
                    return $"Cfg.ArrD({field.name})";
                case SupportableFieldType.Array2D_Int16:
                case SupportableFieldType.Array2D_Int32:
                case SupportableFieldType.Array2D_Int64:
                case SupportableFieldType.Array2D_UInt16:
                case SupportableFieldType.Array2D_UInt32:
                case SupportableFieldType.Array2D_UInt64:
                case SupportableFieldType.Array2D_Boolean:
                    return $"Cfg.Arr2D({field.name})";
                case SupportableFieldType.Array2D_Single:
                    return $"Cfg.Arr2DF({field.name})";
                case SupportableFieldType.Array2D_Double:
                    return $"Cfg.Arr2DD({field.name})";
                default:
                    return field.name;
            }
        }

        private static void AppendCfgStaticClass(
            StringBuilder sb,
            List<(string className, string fullName, string tableName, int tableId)> tables)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 配置表 Id 查询、反序列化注册与 ToString 辅助。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class Cfg");
            sb.AppendLine("    {");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        private static void AutoRegister()");
            sb.AppendLine("        {");
            sb.AppendLine("            ConfigMgr.RegisterDeserializeMethod(Deserialize);");
            sb.AppendLine("            ConfigMgr.RegisterGetTableIdMethod(GetTableId);");
            sb.AppendLine("        }");
            sb.AppendLine();

            AppendGetTableIdMethods(sb, tables);
            AppendDeserializeMethod(sb, tables);
            AppendToStringHelpers(sb);

            sb.AppendLine("    }");
        }

        private static void AppendGetTableIdMethods(
            StringBuilder sb,
            List<(string className, string fullName, string tableName, int tableId)> tables)
        {
            sb.AppendLine("        public static int GetTableId<T>() where T : IConfigTable => GetTableId(typeof(T));");
            sb.AppendLine();
            sb.AppendLine("        public static int GetTableId(Type mapCsharpType)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (mapCsharpType == null) return 0;");
            if (tables.Count == 0)
            {
                sb.AppendLine("            return 0;");
            }
            else
            {
                foreach ((string className, _, _, int tableId) in tables)
                    sb.Append("            if (mapCsharpType == typeof(")
                        .Append(className)
                        .Append(")) return ")
                        .Append(tableId)
                        .AppendLine(";");

                sb.AppendLine("            return 0;");
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static int GetTableId(string tableNameOrFullName)");
            sb.AppendLine("        {");
            if (tables.Count == 0)
            {
                sb.AppendLine("            return 0;");
            }
            else
            {
                sb.AppendLine("            switch (tableNameOrFullName)");
                sb.AppendLine("            {");
                foreach ((_, string fullName, string tableName, int tableId) in tables)
                {
                    sb.Append("                case \"").Append(tableName).AppendLine("\":");
                    sb.Append("                case \"").Append(fullName).Append("\": return ").Append(tableId)
                        .AppendLine(";");
                }

                sb.AppendLine("                default: return 0;");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendDeserializeMethod(
            StringBuilder sb,
            List<(string className, string fullName, string tableName, int tableId)> tables)
        {
            sb.AppendLine("        private static IConfigTable Deserialize(int tableId, in ReadOnlySpan<byte> data)");
            sb.AppendLine("        {");
            if (tables.Count == 0)
            {
                sb.AppendLine("            return null;");
            }
            else
            {
                sb.AppendLine("            switch (tableId)");
                sb.AppendLine("            {");
                foreach ((string className, _, _, int tableId) in tables)
                {
                    sb.Append("                case ").Append(tableId).AppendLine(":");
                    sb.Append("                    return MemoryPackSerializer.Deserialize<")
                        .Append(className)
                        .AppendLine(">(data);");
                }

                sb.AppendLine("                default:");
                sb.AppendLine("                    return null;");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendToStringHelpers(StringBuilder sb)
        {
            sb.AppendLine("        internal static string Num(float v) => v.ToString(\"F2\");");
            sb.AppendLine("        internal static string Num(double v) => v.ToString(\"F2\");");
            sb.AppendLine();
            sb.AppendLine("        internal static string Arr<T>(T[] arr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (arr == null) return \"null\";");
            sb.AppendLine("            return \"[\" + string.Join(\", \", arr) + \"]\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static string ArrF(float[] arr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (arr == null) return \"null\";");
            sb.AppendLine("            if (arr.Length == 0) return \"[]\";");
            sb.AppendLine("            string[] parts = new string[arr.Length];");
            sb.AppendLine("            for (int i = 0; i < arr.Length; i++)");
            sb.AppendLine("                parts[i] = Num(arr[i]);");
            sb.AppendLine("            return \"[\" + string.Join(\", \", parts) + \"]\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static string ArrD(double[] arr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (arr == null) return \"null\";");
            sb.AppendLine("            if (arr.Length == 0) return \"[]\";");
            sb.AppendLine("            string[] parts = new string[arr.Length];");
            sb.AppendLine("            for (int i = 0; i < arr.Length; i++)");
            sb.AppendLine("                parts[i] = Num(arr[i]);");
            sb.AppendLine("            return \"[\" + string.Join(\", \", parts) + \"]\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static string Arr2D<T>(T[][] arr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (arr == null) return \"null\";");
            sb.AppendLine("            if (arr.Length == 0) return \"[]\";");
            sb.AppendLine("            string[] rows = new string[arr.Length];");
            sb.AppendLine("            for (int i = 0; i < arr.Length; i++)");
            sb.AppendLine("                rows[i] = Arr(arr[i]);");
            sb.AppendLine("            return \"[\" + string.Join(\", \", rows) + \"]\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static string Arr2DF(float[][] arr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (arr == null) return \"null\";");
            sb.AppendLine("            if (arr.Length == 0) return \"[]\";");
            sb.AppendLine("            string[] rows = new string[arr.Length];");
            sb.AppendLine("            for (int i = 0; i < arr.Length; i++)");
            sb.AppendLine("                rows[i] = ArrF(arr[i]);");
            sb.AppendLine("            return \"[\" + string.Join(\", \", rows) + \"]\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static string Arr2DD(double[][] arr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (arr == null) return \"null\";");
            sb.AppendLine("            if (arr.Length == 0) return \"[]\";");
            sb.AppendLine("            string[] rows = new string[arr.Length];");
            sb.AppendLine("            for (int i = 0; i < arr.Length; i++)");
            sb.AppendLine("                rows[i] = ArrD(arr[i]);");
            sb.AppendLine("            return \"[\" + string.Join(\", \", rows) + \"]\";");
            sb.AppendLine("        }");
        }
    }
}